
image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo -s exampleSite -d ../public -b "/themen-hugo-35c3-reveal/"
  artifacts:
    paths:
    - public
  only:
  - master

